var artList = [
	{
		"title": "nyoom",
		"description": "old fanart from when i first played ONESHOT. I made it the pinned post on my twitter for some reason.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/nyoom.png",
		"category": "old stuff",
		"date": new Date("2019-12-06T01:05:02Z"),
		"pixellated": "false",
	},
	{
		"title": "karkles",
		"description": "the first homestuck fan art i think i drew? grumpy karkles...", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/HomestuckStuff/KARKAT.png",
		"category": "old stuff",
		"date": new Date("2020-08-06T15:05:17Z"),
		"pixellated": "true",
		
	},
	{
		"title": "TZ",
		"description": "The rezi,,", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/HomestuckStuff/tez.png",
		"category": "old stuff",
		"date": new Date("2021-02-04T00:05:43Z"),
		"pixellated": "true",
	},
	{
		"title": "twitterBanner",
		"description": "my twitter banner! it is unfinished to this day.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/FurryStuff/b%20a%20n%20n%20er.png",
		"category": "old stuff",
		"date": new Date("2020-08-20T21:40:50Z"),
		"pixellated": "false",
	},
	{
		"title": "twitterBannerBG",
		"description": "the painted background for my unfinished twitter banner!",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/FurryStuff/b%20a%20n%20n%20er2.png",
		"category": "old stuff",
		"date": new Date("2020-09-01T16:28:02Z"),
		"pixellated": "false",
	},
	{
		"title": "Chip Run!",
		"description": "sprite for a character from a game i wanted to make, called Hexabullet",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/chiprunnew.gif",
		"category": "old stuff",
		"date": new Date("2020-10-04T10:31:12Z"),
		"pixellated": "true",
	},
	{
		"title": "Cave story!!!",
		"description": "a cute little cave story doodle!",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/cave%20storyyy2.png",
		"category": "old stuff",
		"date": new Date("2020-11-28T10:31:12Z"),
		"pixellated": "true",
	},
	{
		"title": "Sicktune!",
		"description": "they have the sickest tunes, you have no fuckin idea",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/SICKTUNE.png",
		"category": "old stuff",
		"date": new Date("2020-12-07T05:39:03Z"),
		"pixellated": "true",
	},
	{
		"title": "Sicktune 2!",
		"description": "VERY dreamcast",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/Concept.png",
		"category": "old stuff",
		"date": new Date("2020-12-10T12:10:37Z"),
		"pixellated": "true",
	},
	{
		"title": "MintFit",
		"description": "Some cute pixel art of my sona",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/FurryStuff/Mintfit.png",
		"category": "furry",
		"date": new Date("2021-01-15T19:18:51Z"),
		"pixellated": "true",
	},
	{
		"title": "Cascade Day 2022",
		"description": `somethin i did for the 11th anniversary of [S] Cascade.,`,
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/HomestuckStuff/JadeHarleyCascade.png",
		"category": "fanart",
		"date": new Date("2022-10-25T19:18:51Z"),
		"pixellated": "true",
	},	
	{
		"title": "Godfeels.",
		"description": "a little godfeels doodle,",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/HomestuckStuff/godfeels.png",
		"category": "fanart",
		"date": new Date("2023-01-26T20:36:00Z"),
		"pixellated": "true",
	},
	{
		"title": "Parallax Field Of Flowers",
		"description": "I made a whole bunch of pixel art, and then animated some parallax with it >:3<br>please do your best to ignore the tile looping errors on the right", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/FurryStuff/ParallaxFieldOfFlowers.gif",
		"category": "furry",
		"date": new Date("2023-05-15T23:34:54Z"),
		"pixellated": "true",
	},
	{
		"title": "Early Comic Concept Art 1",
		"description": "Literally the earliest thing i drew for tracheotomy, once i had an idea of the vibe i wanted to go for", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/ComicIdeas1.png",
		"category": "tracheotomy",
		"date": new Date("2022-03-04T20:35:59Z"),
		"pixellated": "true",
	},
	{
		"title": "Early Comic Concept Art 2",
		"description": "the SECOND thing i drew for tracheotomy", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/ComicIdeas2.png",
		"category": "tracheotomy",
		"date": new Date("2022-03-04T20:36:00Z"),
		"pixellated": "true",
	},
	{
		"title": "Trainyard",
		"description": "Distant powerlines...", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/Trainyard.png",
		"category": "tracheotomy",
		"date": new Date("2023-01-20T01:13:13Z"),
		"pixellated": "true",
	},
	{
		"title": "Who're these douchebags?",
		"description": "Who're these douchebags?", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/StandingSitting.png",
		"category": "tracheotomy",
		"date": new Date("2023-05-06T01:13:13Z"),
		"pixellated": "true",
	},
	{
		"title": "You Used To Be Happy",
		"description": "Concept art for the comic!", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/YouUsedToBeHappyAprilAsteri.png",
		"category": "tracheotomy",
		"date": new Date("2022-06-23T01:13:13Z"),
		"pixellated": "true",
	},
	{
		"title": "Tracheotomy!!",
		"description": "some promo art for my comic, tried out a noise brush for the shading and i think i'm gonna start using this in the comic proper :0", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/TracheotomyTest.png",
		"category": "tracheotomy",
		"date": new Date("2023-06-06T06:14:48Z"),
		"pixellated": "true",
	},
	{
		"title": "Tracheotomy: Start of year 2",
		"description": "wow it's been a whole year since i started this comic and i'm not even done with the prologue, here's hoping i can up my productivity lmao", 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/StartOfYear2-version2.png",
		"category": "tracheotomy",
		"date": new Date("2023-10-08T00:36:48Z"),
		"pixellated": "true",
	},
	{
		"title": "The qpp's of all time",
		"description": `some doodles based on <a href="https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fffecy0lpixrz.jpg">those humanstuck lapis and peridot designs</a> rebecca sugar did`, 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/humanstuck-lapidot.png",
		"category": "fanart",
		"date": new Date("2023-10-23T19:19:48Z"),
		"pixellated": "true",
	},
	{
		"title": "Lalonde Household",
		"description": `one of my favourite parts of homestuck, aesthetically at least, is the bit during act 1 where rose explores her house<br>the lalonde manor has always stuck with me as a setting for some reason`, 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/HomestuckStuff/LalondeHouse.png",
		"category": "fanart",
		"date": new Date("2024-01-19T16:04:48Z"),
		"pixellated": "true",
	},
	{
		"title": "Art Style Experiment",
		"description": `wanted to get out of my comfort zone for a bit and use some non-pixelly brushes for change, btw this is just what it's like being an artist lmao`, 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/FurryStuff/Art%20Experience.png",
		"category": "furry",
		"date": new Date("2024-01-24T11:30:48Z"),
		"pixellated": "false",
	},
	{
		"title": "Dennis From Chainsaw",
		"description": `chainsaw man is really good you should go read it`, 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/ChainsawDennis.png",
		"category": "fanart",
		"date": new Date("2024-03-31T19:56:48Z"),
		"pixellated": "true",
	},
	{
		"title": "Nighty Woods",
		"description": `i need to replay this game`, 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/MiscStuff/nitw.png",
		"category": "fanart",
		"date": new Date("2024-04-06T19:41:48Z"),
		"pixellated": "false",
	},
	{
		"title": "early character concepts 1",
		"description": "date unknown on these, *some* time from 2022 that;s all i know",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunkown-early-character-concepts1.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "early character concepts 2",
		"description": "proto-laika...",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunkown-early-character-concepts2.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:02Z"),
		"pixellated": "true",
	},
	{
		"title": "early character concepts 3",
		"description": "misc unused designs + an early april",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunkown-early-character-concepts3.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:03Z"),
		"pixellated": "true",
	},
	{
		"title": "early character concepts 4",
		"description": "bold claims made in this one",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunkown-early-character-concepts4.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:04Z"),
		"pixellated": "true",
	},
	{
		"title": "chad buskin",
		"description": "scrapped/heavily reworked character design",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunknown-chadbuskin.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:05Z"),
		"pixellated": "true",
	},
	/*{
		"title": "title",
		"description": "description",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunknown-city.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:06Z"),
		"pixellated": "true",
	},*/
	{
		"title": "early apartment",
		"description": "fun fact: the design for april's apartment was heavily based on a map i made in the genesis project's level editor",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2022-dateunkown-april-apartment.png",
		"category": "tracheotomy",
		"date": new Date("2022-05-01T01:01:07Z"),
		"pixellated": "true",
	},
	{
		"title": "robot designs",
		"description": "another set of sketches with an unclear date. some funky little robot guys. look at 'em go.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2023-robot-designs.png",
		"category": "tracheotomy",
		"date": new Date("2023-01-01T01:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "Dorm room",
		"description": "mysterious dorm room, who could live here?",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2023-07-18-mysterious-dormroom-who-could-it-belong-to.png",
		"category": "tracheotomy",
		"date": new Date("2023-07-18T12:00:00Z"),
		"pixellated": "true",
	},
	{
		"title": "Katia doodles",
		"description": "fun character, she'll show up way later i promise",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2023-08-03-katia-doodles.png",
		"category": "tracheotomy",
		"date": new Date("2023-08-03T12:00:00Z"),
		"pixellated": "true",
	},
	{
		"title": "shirts!",
		"description": "was playin around with april's design just a little",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2023-08-03-shirts.png",
		"category": "tracheotomy",
		"date": new Date("2023-08-03T12:00:00Z"),
		"pixellated": "true",
	},
	{
		"title": "You call this a dystopia!?",
		"description": "Where are all the jumpsuits!?!",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2023-08-3-you-call-this-a-dystopia.png",
		"category": "tracheotomy",
		"date": new Date("2023-08-03T01:01:01Z"),
		"pixellated": "true",
	},
	/*{
		"title": "Callie Doodles",
		"description": "",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/callie-design-2023-08-27-maybe-idk-the-exact-date.png",
		"category": "tracheotomy",
		"date": new Date("2023-08-27T12:01:01Z"),
		"pixellated": "true",
	},*/
	{
		"title": "Colour Test 1",
		"description": "coloured some early pages for funsies",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/ColourTest1.png",
		"category": "tracheotomy",
		"date": new Date("2023-09-14T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "Colour Test 2",
		"description": "ditto",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/ColourTest2.png",
		"category": "tracheotomy",
		"date": new Date("2023-09-14T12:01:02Z"),
		"pixellated": "true",
	},
	{
		"title": "radiohead",
		"description": "i don't know why it's called that",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2024-02-06-radiohead.png",
		"category": "tracheotomy",
		"date": new Date("2024-02-06T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "Door.",
		"description": "ominous.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2024-02-18-door.png",
		"category": "tracheotomy",
		"date": new Date("2024-02-18T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "April Model Sheet",
		"description": "not sure why you'd need this. you're not on my art team. i'm the only one on my art team.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/ModelSheet-AprilMay1.png",
		"category": "tracheotomy",
		"date": new Date("2024-03-13T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "April Fools 2024",
		"description": "fuckin prank'd my idiot followers with this one real good",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2024-04-01-april-fools.png",
		"category": "tracheotomy",
		"date": new Date("2024-04-01T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "Texturebashing Test 1",
		"description": "art style test, was seein how photobashed textures complimented the comic. pretty good turns out.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/PhotoBashTest1.png",
		"category": "tracheotomy",
		"date": new Date("2024-06-12T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "Texturebashing Test 2",
		"description": "ditto.",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/PhotoBashtest2-ver2.png",
		"category": "tracheotomy",
		"date": new Date("2024-06-12T12:01:02Z"),
		"pixellated": "true",
	},
	{
		"title": "You heard of tracheotomy?",
		"description": "where would webcomics as a medium be without control alt delete",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2024-07-03-you-heard-of-tracheotomy.png",
		"category": "tracheotomy",
		"date": new Date("2024-07-03T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "Laika Doodles",
		"description": "Laikaaaaaaaaaa",
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/TracheotomyStuff/2024-07-10-laika-doodles.png",
		"category": "tracheotomy",
		"date": new Date("2024-07-10T12:01:01Z"),
		"pixellated": "true",
	},
	{
		"title": "If I Show My Fangs Will You Tell Me That They're Cool?",
		"description": `haven't been able to draw in a bit! finally got something down for the first time in weeks lol`, 
		"imgUrl": "https://file.garden/Y5hdfT_qkQx7G08g/Art/FurryStuff/mintfangs.png",
		"category": "furry",
		"date": new Date("2024-08-10T00:07:54Z"),
		"pixellated": "true",
	},
]